const focus = document.body.dataset.focus;
const data = {
 education: [['BS in Computer Engineering', 'University of Engineering and Technology, Lahore, Pakistan', '2023 - Expected 2027', 'CGPA: 3.83/4.0 (Top 3 in session). Research Supervisor: Prof. Dr. M. Shahbaz.']],
 experience: [['Aug 2026 - Present','Research Assistant','University of Saskatchewan - KAIT Collaborative Research Project','Diagnosed systematic connector-wire confusion in SegFormer-B5 for deformable linear objects and designed targeted training interventions for three-class RGB segmentation.'],['Jun 2026 - Sep 2026','Research Intern','MITACS Globalink Research Internship, University of Saskatchewan, Saskatoon, Canada','Researched a hybrid AI-Quantum framework for efficient variational circuit design using PennyLane and Qiskit and benchmarked against VQE/QAOA baselines.'],['May 2025 - Jul 2025','Research Intern','National Center for Quantum Computing, Lahore, Pakistan','Developed QAOA-based feature selection for healthcare diagnostics using 2000+ patient samples and implemented a Variational Quantum Classifier achieving 98.4% accuracy.'],['Jun 2024 - Present','Research Assistant','Al-Khawarizmi Institute of Computer Science (KICS), Lahore, Pakistan','Built EEG emotion-recognition pipelines across three datasets and predictive models for Alzheimer’s/MCI classification using 80+ patient EEGs.'],['Mar 2024 - Jun 2024','Machine Learning Intern','Datalabb, Lahore, Pakistan','Designed a U-Net framework for 10k+ medical images, achieving 90% mean Dice score, and fine-tuned domain-adapted LLMs for clinical text.'],['Jun 2024 - Sep 2024','Machine Learning Fellow','Bytewise Limited, Lahore','Selected among the top 9% of 2,300+ applicants; completed 8+ ML projects and reduced preprocessing runtime from 2 days to under 6 hours.'],['Jul 2025 - Present','Research Assistant','Dpoint Technologies Ltd, Cyprus','Researched predictive maintenance for industrial cranes using vibration, temperature, and current sensor data for anomaly detection and fault prediction.']],
 teaching: [['Spring 2026','Teaching Assistant','University of Cyprus','Assisted in Programming Fundamentals and Information Security through labs, assignments, and conceptual clarification.'],['Fall 2025','Teaching Assistant','University of Cyprus','Assisted in Software Engineering and Computer Graphics; guided students in project development, debugging, and applied problem-solving.']],
 projects: [['NeuroAI Platform','Jun 2025 - Present','Python, PyTorch, MNE, ReactJS, Docker, AWS','Built a scalable EEG benchmarking platform with automated parameter prediction and intelligent data-ingestion and annotation workflows. Reduced testing time from 2-3 days to minutes; tested by 5+ researchers in production.'],['Complete Blood Cell Counter','2025','Python, PyTorch, YOLOv11, OpenCV, ONNX, Gradio, Docker','Curated 1,294 annotated microscope images, trained a detector for platelets, RBCs, and WBCs, and deployed an ONNX model in a Dockerized Gradio app. Achieved 97.6% mAP@50 and 94.5% precision on validation data.'],['AI-powered Dental DICOM Annotation System','Jun 2025','Python, PyTorch, U-Net, pydicom, OpenCV, 3D Slicer, Dragonfly','Developed a U-Net model to segment nerves, roots, and enamel in dental CT scans; preprocessed volumetric data and visualized results in 3D Slicer and Dragonfly.'],['Multimodal RAG for Chest X-ray Analysis (MIMIC-CXR)','2025','Python, CLIP, Groq LLM, FAISS, Streamlit','Built cross-modal retrieval over MIMIC-CXR using image-text embeddings and generated structured radiology findings from retrieved clinical cases.'],['AI-Assisted Clinical Exam Preparation','Jul 2024','Python, Meditron LLM, LoRA, QLoRA, PEFT, Transformers','Fine-tuned Meditron for USMLE-style clinical reasoning, reduced annotation workload by 40%, and reached over 92% accuracy in domain validation.'],['IndusTwin: AI-Powered Flood Prediction and Risk Management System','2025','Machine learning, geospatial data, hydrological modeling, digital twins, GIS','Developed a digital-twin-based flood prediction and risk management prototype for Pakistan using AI models, geospatial datasets, and hydrological simulations.']],
 skills: [['Programming & research','Python · C++ · MATLAB · LaTeX · NumPy · Pandas · Matplotlib · OpenCV · MNE'],['Machine learning','PyTorch · TensorFlow · Scikit-learn · Optimization algorithms · Parameter prediction · Continuous learning'],['Specialized computing','Quantum computing · QAOA · Variational quantum classifiers · Predictive modeling · EEG signal processing'],['Engineering tools','ReactJS · Flask · FastAPI · Streamlit · Docker · AWS · MySQL · GitHub · REST APIs']],
 publications: [['2026','TriNet-MTL: A Multi-Branch Deep Learning Framework for Biometric Identification and Cognitive State Inference from Auditory-Evoked EEG','N. Fatima and G. Nabi · eNeuro · Accepted · DOI: 10.1523/ENEURO.0265-25.2025','https://www.eneuro.org/content/13/2/ENEURO.0265-25.2025.abstract'],['2026','Machine Learning-Based Classification for High-Efficiency Perovskite Solar Cell Material Screening','I. Ashfaq, H. Saeed, Z. Uddin, A. Abid and N. Fatima · Proc. 2026 International Conference on Robotics and Automation in Industry (ICRAI), IEEE, May 2026','https://ieeexplore.ieee.org/abstract/document/11551959/'],['2025','Multimodal EEG-Based Classification of Alzheimer’s and MCI Using Olfactory Event-Related Potentials and Transformers','N. Fatima and G. Nabi · Brain-Apparatus Communication · Published','https://doi.org/10.1080/27706710.2025.2602997']],
 awards: [['Excellence in Neuroscience Research','KICS-UET Lahore · June 2025','Recognized for contributions to AI/ML pipelines, signal processing, and computational methods.'],['Chief Minister Punjab’s Honhaar Scholarship','Government of Punjab · May 2025','Awarded for one of the highest CGPAs (top 1%) in Computer Engineering at UET Lahore.'],['Top 6 at Optimized AI Conference 2025','Traversaal.ai · March 2025','Team TROJAN AI ranked among Top 6 out of 200+ global teams.'],['CS50x Puzzle Day 2025','Harvard & MIT · April 2025','Recognized for problem-solving, teamwork, and analytical thinking.'],['National AI Wrapper Competition 2025','Pakistan · 2025','IndusTwin selected among top entries from 2,889 AI project ideas.']],
 certificates: ['Supervised Machine Learning: Regression and Classification - DeepLearning.AI','Deep Learning with PyTorch: Image Segmentation - Coursera Project Network','Introduction to Artificial Intelligence - Google','Fundamentals of Machine Learning - Microsoft','The Nuts and Bolts of Machine Learning - Google','Crash Course on Python - Google','SQL (Basic, Intermediate and Advanced) - HackerRank','AI Agents Fundamentals - Hugging Face','Intro to Deep Learning - Kaggle'],
 talks: [['AI for Brain: Unlocking Cognitive Insights with Machine Learning','ACM UET Lahore Chapter · August 2025','Invited talk engaging 100+ students and faculty in ML applications for neuroscience and predictive modeling.'],['Data-Centric AI: Why Better Data Beats Bigger Models','Google Developer Group (GDG), UET Lahore · August 2025','Invited talk addressing 50+ AI enthusiasts on data quality and intelligent system development.']],
 volunteer: [['Committee Chair (Publicity) & Member','Mediterranean Conference on Emerging Technologies and Systems (MCETS) · Oct 2025 - Present','Leading outreach and visibility strategies and coordinating communication channels for an international academic conference.'],['Member, Society of Artificial Intelligence','International Association of Engineers (IAENG) · Aug 2025 - Present','Engaged in research dissemination, conferences, and technical forums within the AI community.'],['Content Writer','Dr Coders · May 2024 - Jun 2024','Created accessible educational content on programming and coding concepts.'],['Ambassador','AIRCI Expo · Mar 2024 - Apr 2024','Connected industry professionals and supported outreach and event engagement.'],['Student Volunteer (UTS 4.0)','ACM UET Lahore · Feb 2024','Contributed to event decor and collaborated on delivery of the event environment.']],
 training: [['Computational Neuroscience, Neurotechnology and Neuro-inspired AI (ISRC-CN3) Summer School 2026','Intelligent Systems Research Centre, Ulster University, UK · August 2026','Selected online participant; topics included computational neuroscience, neurotechnology, brain-inspired AI, and intelligent systems research.'],['ISDSA 2026 Online Workshops','ICSA and ISDSA · July 2026','EEG Data Analysis Using R; Trustworthy AI; Introduction to Dynamic Network Analysis.']]
};
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const empty = '<p class="empty-state">No entries currently listed.</p>';
const section = (id, label, title, content) => `<section id="${id}" class="section"><div class="section-heading"><p class="eyebrow">${label}</p><h2>${title}</h2></div>${content}</section>`;
const entries = items => items.length ? items : [];
const rows = (items, kind) => entries(items).map(([date, title, org, desc]) => `<article class="role"><time>${esc(date)}</time><div><h3>${esc(title)}</h3><p>${esc(desc)}</p></div><span class="place">${esc(org)}</span></article>`).join('') || empty;
const content = document.querySelector('#content');
document.querySelector('.availability').textContent = focus;
content.innerHTML = section('education','01 · Education','Academic preparation',rows(data.education,'education')) + section('experience','02 · Experience','Research and engineering experience',rows(data.experience)) + section('teaching','03 · Teaching','Teaching assistantship',rows(data.teaching)) + section('projects','04 · Selected work','Projects with a research purpose',`<div class="project-list">${data.projects.map(([title,date,tech,desc],i) => `<article class="project-card"><div class="card-index">${String(i+1).padStart(2,'0')}</div><p class="project-date">${esc(date)}</p><h3>${esc(title)}</h3><p>${esc(desc)}</p><p class="project-tech">${esc(tech)}</p></article>`).join('')}</div>`) + section('skills','05 · Technical profile','Technical skills',`<div class="skill-list">${data.skills.map(([group,skills]) => `<div><h3>${esc(group)}</h3><p>${esc(skills)}</p></div>`).join('')}</div>`) + section('publications','06 · Publications','Selected publications',`<div class="publication-list">${data.publications.map(([year,title,meta,link]) => `<article class="publication"><div><span class="pub-status">${meta.includes('Accepted')?'Accepted':'Published'}</span><h3>${esc(title)}</h3><p>${esc(meta)}</p><a href="${link}" target="_blank" rel="noreferrer">Read publication ↗</a></div><div class="pub-meta">${esc(year)}</div></article>`).join('')}</div>`) + section('awards','07 · Honors','Honors & awards',rows(data.awards)) + section('certificates','08 · Continuing education','Relevant certificates',`<div class="plain-list">${data.certificates.map(item => `<p>${esc(item)}</p>`).join('')}</div>`) + section('talks','09 · Academic communication','Invited talks',rows(data.talks)) + section('volunteer','10 · Service','Volunteer experience',rows(data.volunteer)) + section('training','11 · Academic training','Summer schools & academic training',rows(data.training)) + section('contact','12 · Contact','Open to thoughtful collaboration',`<div class="contact-links"><a href="mailto:noorfatimaafzalbutt@gmail.com">noorfatimaafzalbutt@gmail.com</a><a href="Noor_CV.pdf" download>Download CV ↓</a></div>`);
const links = [['Certificates','certificates'],['Talks','talks'],['Volunteer','volunteer'],['Training','training']]; document.querySelector('nav').insertAdjacentHTML('beforeend', links.map(([label,id]) => `<a href="#${id}">${label}</a>`).join(''));
const menu = document.querySelector('.menu-toggle'); menu.addEventListener('click', () => { const nav = document.querySelector('nav'); const open = nav.classList.toggle('open'); menu.setAttribute('aria-expanded', String(open)); }); document.querySelectorAll('nav a').forEach(link => link.addEventListener('click', () => { document.querySelector('nav').classList.remove('open'); menu.setAttribute('aria-expanded','false'); }));
